
import os
import sys

print("=" * 70)
print("        Person Segmentation - Data Preparation Helper")
print("=" * 70)
print()

print("This script will help you prepare training data for person segmentation.")
print()

print("OPTION 1: Download Public Dataset")
print("-" * 70)
print()
print("Recommended datasets:")
print()
print("1. Supervisely Person Dataset")
print("   - Images: 5711")
print("   - Quality: High")
print("   - URL: https://supervisely.com")
print("   - Steps:")
print("     a) Visit the website and create a free account")
print("     b) Download 'Person' dataset")
print("     c) Extract images to: dataset/train/image/")
print("     d) Extract masks to: dataset/train/label/")
print()

print("2. Pascal VOC 2012")
print("   - Images: ~3000 (person class)")
print("   - Quality: High")
print("   - URL: http://host.robots.ox.ac.uk/pascal/VOC/")
print("   - Steps:")
print("     a) Download VOCtrainval_11-May-2012.tar")
print("     b) Extract the tar file")
print("     c) Copy person images from JPEGImages/ to dataset/train/image/")
print("     d) Convert and copy person masks from SegmentationClass/ to dataset/train/label/")
print()

print("3. COCO Dataset")
print("   - Images: Large scale")
print("   - Quality: High")
print("   - URL: https://cocodataset.org/")
print("   - Note: Requires more processing")
print()

print()
print("OPTION 2: Create Your Own Dataset")
print("-" * 70)
print()
print("Steps:")
print("1. Collect person photos (100+ recommended)")
print("2. Use annotation tool to create masks:")
print("   - LabelMe: https://github.com/wkentaro/labelme")
print("   - VGG VIA: http://www.robots.ox.ac.uk/~vgg/software/via/")
print("3. Save images to: dataset/train/image/")
print("4. Save masks to: dataset/train/label/")
print()

print()
print("OPTION 3: Use Sample Data for Testing")
print("-" * 70)
print()
print("If you just want to test the code, you can:")
print("1. Find 10-20 person photos online")
print("2. Use any image editor to create rough masks")
print("3. Train with small dataset to verify the pipeline works")
print()

print()
print("=" * 70)
print("Data Format Requirements")
print("=" * 70)
print()
print("Training Images:")
print("  - Format: JPG or PNG")
print("  - Color: RGB")
print("  - Size: Any (will be resized to 256x256)")
print("  - Location: dataset/train/image/")
print("  - Naming: 0.jpg, 1.jpg, ... or any name")
print()

print("Training Masks (Labels):")
print("  - Format: PNG")
print("  - Color: Grayscale")
print("  - Size: Same as corresponding image")
print("  - Location: dataset/train/label/")
print("  - Naming: Same as image name")
print("  - Content:")
print("    * White (255) = Person")
print("    * Black (0) = Background")
print()

print("Test Images:")
print("  - Format: JPG or PNG")
print("  - Color: RGB")
print("  - Size: Any")
print("  - Location: dataset/test/")
print("  - Naming: 0.jpg, 1.jpg, ... or 0.png, 1.png, ...")
print()

print()
print("=" * 70)
print("Quick Start Checklist")
print("=" * 70)
print()
print("□ Download or create training images")
print("□ Create or download training masks")
print("□ Put images in dataset/train/image/")
print("□ Put masks in dataset/train/label/")
print("□ Verify image-mask pairs match")
print("□ Run: python train_person.py")
print("□ Add test images to dataset/test/")
print("□ Run: python predict_person.py")
print("□ Check results in dataset/test/")
print()

print()
print("=" * 70)
print("Need Help?")
print("=" * 70)
print()
print("If you have questions:")
print("1. Check README.txt for detailed instructions")
print("2. Make sure data format is correct")
print("3. Verify file paths and names")
print()
